webserver/dashboard/urls.py
from django.urls import path 
from . import views 


app_name = "dashboard"

urlpatterns = [
    path('' , views.home , name='home'),
    path('signup/' , views.sign_up , name="signup"),
    path('add_team/' , views.add_team , name="add_team"), 
    path('create_user/' ,views.create_user , name="create_user" ),
    path('send_mood/', views.MoodView.as_view(), name="Mood"),
    path("add_new_token/" , views.add_new_token , name="add_new_token" ),
    path("update_repo/" , views.update_repo , name="update_repo"),   
    path("suppressTeam/" , views.suppressTeam , name="suppressTeam"),
    path("team_view/" , views.team_view , name="team_view"),   
]

webserver/llmcoach/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views 

app_name = "llmcoach"

urlpatterns = [
    path("" , views.home , name="llmcoach") , 
    path("home" , views.home , name="home") ,
    path("chat" , views.CHAT , name="chat") ,
    path("evaluation" , views.EVALUATION , name="evaluation"),
]

webserver/webserver/urls.py
from django.contrib import admin
from django.urls import include, path
import django_cas_ng.views


urlpatterns = [
    path('admin/', admin.site.urls),
    path("" , include('dashboard.urls')), 
    #path("dashboard/" , include('dashboard.urls' )), 

    path("" , include('django.contrib.auth.urls')), 
    path('cas/login', django_cas_ng.views.LoginView.as_view(), name='cas_ng_login'),
    path('cas/logout', django_cas_ng.views.LogoutView.as_view(), name='cas_ng_logout'),
    path("llmcoach/" , include("llmcoach.urls")) , 

] 

webserver/templates/includes/navigation.html
{% load static %}

<header class="navbar pcoded-header navbar-expand-lg navbar-light">
  <div class="m-header">
    <a class="mobile-menu" id="mobile-collapse1" href="javascript:"><span></span></a>
    <a href="{% url 'dashboard:home' %}" class="b-brand">
      <div class="b-bg">
        <i class="feather icon-trending-up"></i>
      </div>
      <span class="b-title">Datta Able</span>
    </a>
  </div>
  <a class="mobile-menu" id="mobile-header" href="javascript:">
    <i class="feather icon-more-horizontal"></i>
  </a>
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <li><a href="javascript:" class="full-screen" onclick="javascript:toggleFullScreen()"><i
            class="feather icon-maximize"></i></a></li>
      {% comment %} <li class="nav-item dropdown">
        <a class="dropdown-toggle" href="javascript:" data-toggle="dropdown">Dropdown</a>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="javascript:">Action</a></li>
          <li><a class="dropdown-item" href="javascript:">Another action</a></li>
          <li><a class="dropdown-item" href="javascript:">Something else here</a></li>
        </ul>
      </li> {% endcomment %}
      {% comment %} <li class="nav-item">
        <div class="main-search">
          <div class="input-group">
            <input type="text" id="m-search" class="form-control" placeholder="Search . . .">
            <a href="javascript:" class="input-group-append search-close">
              <i class="feather icon-x input-group-text"></i>
            </a>
            <span class="input-group-append search-btn btn btn-primary">
              <i class="feather icon-search input-group-text"></i>
            </span>
          </div>
        </div>
      </li> {% endcomment %}
    </ul>
    <ul class="navbar-nav ml-auto">
      <li>
        <label>
          <i class="icon feather icon-sun" id="theme-indicator"></i>
          <input type="checkbox" id="theme-switch" class="d-none">
        </label>
      </li>
      {% comment %}
      <li>
        <div class="dropdown">
          <a class="dropdown-toggle" href="javascript:" data-toggle="dropdown"><i
              class="icon feather icon-bell"></i></a>
          <div class="dropdown-menu dropdown-menu-right notification">
            <div class="noti-head">
              <h6 class="d-inline-block m-b-0">Notifications</h6>
              <div class="float-right">
                <a href="javascript:" class="m-r-10">mark as read</a>
                <a href="javascript:">clear all</a>
              </div>
            </div>
            <ul class="noti-body">
              <li class="n-title">
                <p class="m-b-0">NEW</p>
              </li>
              <li class="notification">
                <div class="media">
                  <img class="img-radius" src="{% static 'assets/images/user/avatar-1.jpg' %}" alt="Generic placeholder image">
                  <div class="media-body">
                    <p><strong>John Doe</strong><span class="n-time text-muted"><i
                          class="icon feather icon-clock m-r-10"></i>30 min</span></p>
                    <p>New ticket Added</p>
                  </div>
                </div>
              </li>
              <li class="n-title">
                <p class="m-b-0">EARLIER</p>
              </li>
              <li class="notification">
                <div class="media">
                  <img class="img-radius" src="{% static 'assets/images/user/avatar-2.jpg' %}" alt="Generic placeholder image">
                  <div class="media-body">
                    <p><strong>Joseph William</strong><span class="n-time text-muted"><i
                          class="icon feather icon-clock m-r-10"></i>30 min</span></p>
                    <p>Prchace New Theme and make payment</p>
                  </div>
                </div>
              </li>
              <li class="notification">
                <div class="media">
                  <img class="img-radius" src="{% static 'assets/images/user/avatar-3.jpg' %}" alt="Generic placeholder image">
                  <div class="media-body">
                    <p><strong>Sara Soudein</strong><span class="n-time text-muted"><i
                          class="icon feather icon-clock m-r-10"></i>30 min</span></p>
                    <p>currently login</p>
                  </div>
                </div>
              </li>
            </ul>
            <div class="noti-footer">
              <a href="javascript:">show all</a>
            </div>
          </div>
        </div>
      </li>
      {% endcomment %}
      <li>
        <div class="dropdown drp-user">
          <a href="javascript:" class="dropdown-toggle" data-toggle="dropdown">
            <i class="icon feather icon-settings"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right profile-notification">
            <div class="pro-head">
              <img src="{% static 'assets/images/user/avatar-1.jpg' %}" class="img-radius" alt="User-Profile-Image">
              <span>{{ data.coach_data.user }}</span>
              {% if request.user.is_authenticated %}
                {% if request.user.is_superuser %}
                <a href="{% url 'admin:logout' %}" class="dud-logout" title="Logout">
                {% else %}
                <a href="{% url 'logout' %}" class="dud-logout" title="Logout">
                {% endif %}
                  <i class="feather icon-log-out"></i>
                </a>
              {% endif %}
            </div>
            {% comment %} <ul class="pro-body">
              <li><a href="#" class="dropdown-item"><i class="feather icon-settings"></i>
                  Settings</a></li>
              <li><a href="#" class="dropdown-item"><i class="feather icon-user"></i>
                  Profile</a></li>
              <li><a href="#" class="dropdown-item"><i class="feather icon-mail"></i> My
                  Messages</a></li>
              <li><a href="#" class="dropdown-item"><i class="feather icon-lock"></i> Lock
                  Screen</a></li>
              {% if request.user.is_authenticated %}
              <li>
                {% if request.user.is_superuser %}
                <a href="{% url 'admin:password_change' %}" class="dropdown-item">
                {% else %}
                <a href="{% url 'password_change' %}" class="dropdown-item">
                {% endif %}
                  <i class="feather icon-edit"></i>Change Password
                </a>
              </li>
              {% endif %}
            </ul> {% endcomment %}
          </div>
        </div>
      </li>
    </ul>
  </div>
</header>

webserver/templates/includes/sidebar.html
{% comment %} {% load i18n static admin_datta %} {% endcomment %}

{% block extrastyle %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock extrastyle %}

<nav class="pcoded-navbar">
  <div class="navbar-wrapper">
    <div class="navbar-brand header-logo">
      <a href="{% url 'dashboard:home' %}" class="b-brand">
        <div class="b-bg">
          <i class="feather icon-trending-up"></i>
        </div>
        <span class="b-title">Coding coach</span>
      </a>
      <a class="mobile-menu" id="mobile-collapse" href="javascript:"><span></span></a>
    </div>
    <div class="navbar-content scroll-div">
      <ul class="nav pcoded-inner-navbar">
        {% if request.user.is_authenticated %}
        <li class="nav-item pcoded-menu-caption">
          <a href="{% url 'dashboard:home' %}"><i class="fa fa-table"></i> Dashboard</a>
        </li>
        <li class="nav-item pcoded-menu-caption">
          <a href="{% url 'llmcoach:llmcoach' %}"><i class="fa fa-commenting" aria-hidden="true"></i> LLM coach</a>
        </li>
        <li class="nav-item pcoded-menu-caption">
          <a href="{% url 'llmcoach:chat' %}"><i class="fa fa-commenting" aria-hidden="true"></i> Code question</a>
        </li>
        <li class="nav-item pcoded-menu-caption">
          <a href="{% url 'llmcoach:evaluation' %}"><i class="fa fa-commenting" aria-hidden="true"></i> Code evaluation</a>
        </li>
        <li class="nav-item pcoded-menu-caption">
          <a href="{% url 'dashboard:add_new_token' %}"><i class="fa fa-plus"></i> Add teams</a>
        </li>
        <li class="nav-item pcoded-menu-caption">
          <a href="{% url 'logout' %}"><i class="fa fa-sign-out"></i> Log out</a>
        </li>
        {% endif %}

        {% comment %} <li data-username="dashboard Default Ecommerce CRM Analytics Crypto Project" class="nav-item {% if 'index' in segment %}active{% endif %}">
          {% if request.user.is_superuser %}
          <a href="{% url 'admin:index' %}" class="nav-link ">
          {% else %}
          <a href="{% url 'index' %}" class="nav-link ">
          {% endif %}
            <span class="pcoded-micon"><i class="feather icon-home"></i></span><span class="pcoded-mtext">Dashboard</span>
          </a>
        </li> {% endcomment %}
        {% comment %} <li class="nav-item {% if 'tables' in segment %}active{% endif %}">
          <a href="{% url 'tables' %}" class="nav-link "><span class="pcoded-micon"><i
                class="feather icon-server text-c-green"></i></span><span class="pcoded-mtext">Dynamic Tables</span></a>
        </li>  {% endcomment %}

        {% if not request.user.is_authenticated %}
          <ul class="nav pcoded-inner-navbar">
            <li class="nav-item pcoded-menu-caption">
              <a href="{% url 'cas_ng_login' %}" class="">Sign in with CAS</a>
            </li>
            <li class="nav-item pcoded-menu-caption">
              <a href="{% url 'login' %}" class="">Sign in</a>
            </li>
            <li class="nav-item pcoded-menu-caption">
              <a href="{% url 'dashboard:signup' %}" class="">Sign up</a>
            </li>
          </ul> 
        {% endif %}

        {% comment %} {% admin_get_menu as app_list %} {% endcomment %}
        {% if app_list %}
          {% for app in app_list %}
            {% if app.has_perms and not app.pinned %}
              <li 
                data-username="basic components Button Alert Badges breadcrumb Paggination progress Tooltip popovers Carousel Cards Collapse Tabs pills Modal Grid System Typography Extra Shadows Embeds"
                class="nav-item pcoded-hasmenu"
              >
                <a href="javascript:" class="nav-link ">
                  <span class="pcoded-micon"><i class=" {% if app.icon %}{{ app.icon }} {% else %} feather icon-box {% endif %}"></i></span>
                  <span class="pcoded-mtext">{{ app.label|slice:10 }}{% if app.label|length > 10 %}..{% endif %}</span>
                </a>
                {% if app.models %}
                  <ul class="pcoded-submenu">
                    {% for model in app.models %}
                      {% if model.url %}
                        <li class="nav-item {% if 'bootstrap-tables' in segment or model.url in request.path|urlencode %} active {% endif %}">
                          <a class="nav-link" href="{{ model.url }}">{{ model.label }}</a>
                        </li>
                      {% else %}
                        <li class="nav-item">{{ model.label }}</li>
                      {% endif %}
                    {% endfor %}
                  </ul>
                {% endif %}
              </li>
            {% endif %}
          {% endfor %}
        {% endif %}

        {% if request.user.is_authenticated and not request.user.is_superuser %}
        {% comment %} <li
          data-username="basic components Button Alert Badges breadcrumb Paggination progress Tooltip popovers Carousel Cards Collapse Tabs pills Modal Grid System Typography Extra Shadows Embeds"
          class="nav-item pcoded-hasmenu {% if 'basic_components' in parent %}active pcoded-trigger{% endif %}">
          <a href="javascript:" class="nav-link "><span class="pcoded-micon"><i
                class="feather icon-box"></i></span><span class="pcoded-mtext">Components</span></a>
          <ul class="pcoded-submenu">
            <li class="{% if 'button' in segment %}active{% endif %}"><a href="{% url 'bc_button' %}" class="">Button</a></li>
            <li class="{% if 'badges' in segment %}active{% endif %}"><a href="{% url 'bc_badges' %}" class="">Badges</a></li>
            <li class="{% if 'breadcrumbs_&_pagination' in segment %}active{% endif %}"><a href="{% url 'bc_breadcrumb_pagination' %}" class="">Breadcrumb & paggination</a></li>
            <li class="{% if 'collapse' in segment %}active{% endif %}"><a href="{% url 'bc_collapse' %}" class="">Collapse</a></li>
            <li class="{% if 'navs_&_tabs' in segment %}active{% endif %}"><a href="{% url 'bc_tabs' %}" class="">Tabs & pills</a></li>
            <li class="{% if 'typography' in segment %}active{% endif %}"><a href="{% url 'bc_typography' %}" class="">Typography</a></li>


            <li class="{% if 'feather_icon' in segment %}active{% endif %}"><a href="{% url 'icon_feather' %}" class="">Feather<span
                  class="pcoded-badge label label-danger">NEW</span></a></li>
          </ul>
        </li> {% endcomment %}
        {% comment %} <li class="nav-item pcoded-menu-caption">
          <label>Forms & table</label>
        </li> {% endcomment %}
        {% comment %} <li data-username="form elements advance componant validation masking wizard picker select" class="nav-item {% if 'form_elements' in segment %}active{% endif %}">
          <a href="{% url 'form_elements' %}" class="nav-link "><span class="pcoded-micon"><i
                class="feather icon-file-text"></i></span><span class="pcoded-mtext">Form elements</span></a>
        </li>
        <li data-username="Table bootstrap datatable footable" class="nav-item {% if 'basic_tables' in segment %}active{% endif %}">
          <a href="{% url 'basic_tables' %}" class="nav-link "><span class="pcoded-micon"><i
                class="feather icon-server"></i></span><span class="pcoded-mtext">Table</span></a>
        </li> {% endcomment %}
        {% comment %} <li data-username="Profile Page" class="nav-item {% if 'profile' in segment %}active{% endif %}"><a href="{% url 'profile' %}" class="nav-link"><span
              class="pcoded-micon"><i class="feather icon-user"></i></span><span class="pcoded-mtext">Profile
              Page</span></a>
        </li> {% endcomment %}
        {% comment %} <li data-username="Sample Page" class="nav-item {% if 'sample_page' in segment %}active{% endif %}"><a href="{% url 'sample_page' %}" class="nav-link"><span
              class="pcoded-micon"><i class="feather icon-sidebar"></i></span><span class="pcoded-mtext">Sample
              page</span></a>
        </li>
        <li data-username="Disabled Menu" class="nav-item disabled"><a href="javascript:" class="nav-link"><span
              class="pcoded-micon"><i class="feather icon-power"></i></span><span class="pcoded-mtext">Disabled
              menu</span></a>
        </li> {% endcomment %}
        {% endif %}
      </ul>
    </div>
  </div>
</nav>