webserver/dashboard/urls.py
from django.urls import path 
from . import views 


app_name = "dashboard"

urlpatterns = [
    path('' , views.home , name='home'),
    path('signup/' , views.sign_up , name="signup"),
    path('add_team/' , views.add_team , name="add_team"), 
    path('create_user/' ,views.create_user , name="create_user" ),
    path('send_mood/', views.MoodView.as_view(), name="Mood"),
    path("add_new_token/" , views.add_new_token , name="add_new_token" ),
    path("update_repo/" , views.update_repo , name="update_repo"),   
    path("suppressTeam/" , views.suppressTeam , name="suppressTeam"),
    path("team_view/" , views.team_view , name="team_view"),   
]

webserver/llmcoach/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views 

app_name = "llmcoach"

urlpatterns = [
    path("" , views.home , name="llmcoach") , 
    path("home" , views.home , name="home") ,
    path("chat" , views.CHAT , name="chat") ,
    path("evaluation" , views.EVALUATION , name="evaluation"),
]

webserver/webserver/urls.py
from django.contrib import admin
from django.urls import include, path
import django_cas_ng.views


urlpatterns = [
    path('admin/', admin.site.urls),
    path("" , include('dashboard.urls')), 
    #path("dashboard/" , include('dashboard.urls' )), 

    path("" , include('django.contrib.auth.urls')), 
    path('cas/login', django_cas_ng.views.LoginView.as_view(), name='cas_ng_login'),
    path('cas/logout', django_cas_ng.views.LogoutView.as_view(), name='cas_ng_logout'),
    path("llmcoach/" , include("llmcoach.urls")) , 

] 

webserver/dashboard/models.py
from django.db import models
from django.contrib.auth.models import User, BaseUserManager



class Utilisateur(models.Model):
    id = models.AutoField(primary_key=True)
    #email = models.EmailField(unique=True , bla)
    username = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.username

class GitlabAccessRepo(models.Model):
    id = models.AutoField(primary_key=True)  
    token = models.CharField(max_length=255)
    url = models.URLField()
    projectName = models.CharField(max_length=255)



class TeamMood(models.Model):
    timeStamp = models.DateTimeField(auto_now_add=True)
    moodLevel = models.IntegerField()
    message = models.TextField()

    def __str__(self):
        if self.moods.first():
            return f"{self.moods.first().teamName} - {self.timeStamp}"
        else:
            return "No team - {self.timeStamp}"


class TeamRepo(models.Model):
    timeStamp = models.DateTimeField(auto_now_add=True)
    branchNumber = models.IntegerField()
    branchBehindMax = models.IntegerField()
    branchAheadMax = models.IntegerField()
    lastPrTime = models.DateTimeField(null=True, blank=True)
    commitQuality = models.IntegerField()

    def __str__(self):
        return f"TeamRepo - {self.timeStamp}"


class TeamTable(models.Model):
    teamId = models.AutoField(primary_key=True)
    teamName = models.CharField(max_length=255)
    gitlabRepo = models.ForeignKey(GitlabAccessRepo, related_name="gitlabAccess", on_delete=models.CASCADE, unique=False)
    users = models.ManyToManyField(Utilisateur, related_name='teams', blank=True)
    moods = models.ManyToManyField(TeamMood , related_name="moods" , blank=True ) 
    repos = models.ManyToManyField(TeamRepo , related_name="repos" , blank=True )

    def __str__(self):
        return self.teamName

#OBJECTIVE     
class Coach(User):    
    teams = models.ManyToManyField(TeamTable , related_name='teams' , blank=True)

    def __str__(self):
        return self.username






class CoachCas(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    teams = models.ManyToManyField(TeamTable, related_name='coaches', blank=True)

    def __str__(self):
        return self.user.username

webserver/dashboard/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm 
from django.contrib.auth.models import User

from .models import Coach, TeamTable, GitlabAccessRepo

# class CoachCreationForm(forms.ModelForm):
#     password = forms.CharField(widget=forms.PasswordInput)

#     class Meta:
#         model = CoachTable
#         fields = ['email', 'username', 'password']

# class TeamCreationForm(forms.ModelForm):
#     class Meta:
#         model = TeamTable
#         fields = ['teamName', 'teamGitlabAccessToken']



class RegisterForm(UserCreationForm):
    #email = forms.EmailField(required=True)
    class Meta:
        model = Coach 
        fields = [ "username"  ,'password1' , "password2"]


class TeamTableForm(forms.ModelForm):
    coachs = forms.ModelMultipleChoiceField(queryset=Coach.objects.all(), widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = TeamTable
        fields = ['teamName', 'repos', 'coachs']

class GitlabAccessRepoForm(forms.ModelForm):
    class Meta:
        model = GitlabAccessRepo
        fields = ['url', 'token', 'projectName']

webserver/dashboard/views.py
import datetime
from django.http import HttpRequest, HttpResponse
from .models import Coach, CoachCas, GitlabAccessRepo, TeamMood, TeamRepo, TeamTable, Utilisateur
from django.contrib.auth.models import User, BaseUserManager

from.serializers import MoodSerializer
from .forms import GitlabAccessRepoForm, RegisterForm, TeamTableForm 
from django.shortcuts import redirect, render
from django.contrib.auth import login , logout , authenticate 
from django.contrib.auth.decorators import login_required , user_passes_test
from rest_framework import status
# Create your views here.

from utils import gitAPI
from rest_framework.views import APIView
from rest_framework.renderers import JSONRenderer
from rest_framework.response import Response
import utils.gitAPI as gitAPI
import random

def redirect_authenticated_user(view_func):
    def wrapper(request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect("/")
        return view_func(request, *args, **kwargs)
    return wrapper



@user_passes_test(lambda u: u.is_authenticated or u.is_superuser, login_url="/login")
def home(request):
    user = request.user
    
    # Try to retrieve CoachCas instance for the authenticated CAS user
    coach = None 
    try: 
        coach = CoachCas.objects.get(user=user) 
    except:
        coach = CoachCas.objects.create(user=user)




    print("COACH " , coach)

    print(coach.user)
    print(coach.teams)


    # Retrieve all teams managed by the coach
    teams_managed_by_coach = coach.teams.all()
    print(teams_managed_by_coach)
    # Create dictionaries to store users, moods, and repos for each team
    team_data = {}
    gitlab_access_repo_info = {}

   
    for team in teams_managed_by_coach:
        print("TEAM " , team ) 

        # Retrieve users, moods, and repos for each team
        users = team.users.all()
        moods = team.moods.all()
        repos = team.repos.all()
        if repos:
            last_repo = repos.latest('timeStamp')
        else:
            last_repo = repos
        
        # Retrieve GitLab information using the stored GitLab access token and repository URL
        gitlab_repo = team.gitlabRepo

        # Retrieve information from the GitlabAccessRepo model
        gitlab_access_repo_info = {
            'token': gitlab_repo.token,
            'url': gitlab_repo.url,
            'projectName': gitlab_repo.projectName,
        }
        
        average_mood = 0
        n = 0
        for user in users:
            n += 1
        i=0
        if moods.exists() and users.exists():
            day = moods[0].timeStamp.day
            for mood in moods:
                if mood.timeStamp.day == day:
                    average_mood += mood.moodLevel
                    if i == n:
                        break
                    i += 1
            average_mood = average_mood/n
        else:
            average_mood = -1
            
        team_data[team] = {
            'users': users,
            'mood': average_mood,
            'repo': last_repo,
            'gitlab_access_repo_info': gitlab_access_repo_info,
        }
    
    data = {}
    data['team_data'] = team_data
    data['coach_data'] = {'user': coach.user.username}    

    return render(request, 'dashboard/index.html', {'data': data})



@login_required(login_url="/login")
def update_repo(request):
    print("------------UPDATE REPO---------------")
    # Assuming the logged-in user is a coach
    user = request.user
    coach = CoachCas.objects.get(user=user)

    # Retrieve all teams managed by the coach
    teams_managed_by_coach = coach.teams.all()

    print("TEAMS UNDER SUPERVISION : " , teams_managed_by_coach)

    for team in teams_managed_by_coach:
        # Retrieve GitLab information using the stored GitLab access token and repository URL
        gitlab_repo = team.gitlabRepo

        # Retrieve information from the GitlabAccessRepo model
        gitlab_access_repo_info = {
            'token': gitlab_repo.token,
            'url': gitlab_repo.url,
            'projectName': gitlab_repo.projectName,
        }

        # Compute information using the gitAPI.compute_all function
        computed_info = gitAPI.compute_all(
            gitlab_access_repo_info['url'],
            gitlab_access_repo_info['token'],
            gitlab_access_repo_info['projectName']
        )

        print("-----------------------------------------")
        #print(computed_info)

        # Create an instance of TeamRepo and save the computed information
        team_repo = TeamRepo(
            branchNumber=computed_info['get_branch_number'],
            branchBehindMax=computed_info['most_behind_branch'],
            branchAheadMax=computed_info['most_ahead_branch'],
            lastPrTime=computed_info['last_PR_time'],
            commitQuality=computed_info['rate_commit'],
        )
        team_repo.save()
        print(team_repo)
        # Add the TeamRepo instance to the current team
        team.repos.add(team_repo)

    return redirect("/")

@login_required(login_url="/login")
def suppressTeam(request):
    user = request.user
    coach = CoachCas.objects.get(user=user)

    # Retrieve the team to suppress
    team_name = request.GET.get('teamName','None')
    team = coach.teams.get(teamName=team_name)

    coach.teams.remove(team)
    
    coach.save()

    return redirect("/")


@login_required(login_url="/login")
def team_view(request):
    # Assuming the logged-in user is a coach
    user = request.user 
    coach = CoachCas.objects.get(user=user) 
    
    # Retrieve the team
    team_name = request.GET.get('teamName','None')
    team = coach.teams.get(teamName=team_name)

    # Create dictionaries to store users, moods, and repos for each team
    data = {}
    gitlab_access_repo_info = {}

    # Retrieve users, moods, and repos for each team
    users = team.users.all()
    moods = team.moods.all()
    repos = team.repos.all()
    if repos:
        last_repo = repos.latest('timeStamp')
    else:
        last_repo = repos
    
    # Retrieve GitLab information using the stored GitLab access token and repository URL
    gitlab_repo = team.gitlabRepo

    # Retrieve information from the GitlabAccessRepo model
    gitlab_access_repo_info = {
        'token': gitlab_repo.token,
        'url': gitlab_repo.url,
        'projectName': gitlab_repo.projectName,
    }
    
    data['team'] = {
        'name':team_name,
        'users': users,
        'moods': moods,
        'repo': last_repo,
        'gitlab_access_repo_info': gitlab_access_repo_info,
    }
    
    data['coach'] = {'user': coach.user.username}    

    return render(request, 'dashboard/repo.html', {'data': data})


@login_required(login_url="/login")
def add_team(request):
    if request.method == 'POST':
        form = TeamTableForm(request.POST)
        if form.is_valid():
            team = form.save(commit=False)
            # Set additional fields if needed
            team.save()
            return redirect('dashboard:home')  # Redirect to the appropriate page after saving
    else:
        # Set the initial data for the form
        initial_data = {'coachs': [request.user.id]}
        form = TeamTableForm(initial=initial_data)

    return render(request, 'dashboard/add_team.html', {'form': form})





@redirect_authenticated_user
def sign_up(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request , user  , backend='django.contrib.auth.backends.ModelBackend')
            return redirect("/")

    else:
        form = RegisterForm()
    
    return render(request , "registration/signup.html" , {"form" :  form })


@user_passes_test(lambda u: u.is_superuser)
def create_user(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('user_list')  # Redirect to the user list page or any other page
    else:
        form = RegisterForm()

    return render(request, 'registration/create_user.html', {'form': form})


class MoodView(APIView):
    def post(self, request, format=None):
        serializer = MoodSerializer(data=request.data)

        if serializer.is_valid():
            # Valid data
            moodLevel = serializer.validated_data['moodLevel']
            message = serializer.validated_data['message']
            projectName = serializer.validated_data['projectName']
            
            # Fetch GitlabAccessRepo by projectName
            try:
                #repo = GitlabAccessRepo.objects.get(projectName=projectName)
                repos = GitlabAccessRepo.objects.filter(projectName=projectName)
            except GitlabAccessRepo.DoesNotExist:
                return Response({'status': 'error', 'message': 'Repo not found for the given projectName'}, 
                                status=status.HTTP_404_NOT_FOUND)
            
            for repo in repos:
                team = repo.gitlabAccess.first()
                
                if team:
                    mood = TeamMood.objects.create(timeStamp=datetime.datetime.now(), moodLevel=moodLevel, message=message)
                    team.moods.add(mood)
                
            return Response({'status': 'success',
                            'message': 'Data received and processed successfully'},
                            status=status.HTTP_201_CREATED)
        else:
            # Invalid data
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


#@require_http_methods(["GET", "POST"])

# views.py
#https://gitlab.paris-digital-lab.com
#glpat-GdDcjCKWycUxtFzpqvnG

@login_required(login_url="/login")
def add_new_token(request):
    if request.method == 'GET':
        # If the method is GET, redirect to a new page to display repositories
        form = GitlabAccessRepoForm()

webserver/templates/dashboard/add_team.html
{% extends 'layouts/base.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'assets/css/customForm.css' %}">
{% block content %}

  <h2>Add Team</h2>
  <form method="post" action="{% url 'dashboard:add_team' %}">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Save</button>
  </form>
{% endblock %}

webserver/templates/dashboard/add_team_save.html
{% extends 'layouts/base.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">
{% block content %}

  <h2>Add Team</h2>
  <form method="post" action="{% url 'dashboard:add_team' %}">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Save</button>
  </form>
{% endblock %}

webserver/templates/dashboard/index.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block extrastyle %}

<link rel="stylesheet" href="{% static 'assets/css/customIndex.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<style>
  /* Responsive table */
  .table-responsive {
      overflow-x:hidden ;
  }

  /* Word wrapping in table cells */
  .table td, .table th {
      white-space: normal;
      word-wrap: break-word;
  }

  /* Responsive design for smaller screens */
  @media (max-width: 768px) {
      .grid {
          grid-template-columns: 1fr; /* Single column layout on smaller screens */
      }
  }

  /* Additional styles to separate buttons and handle long team names */
.table .a {
  margin-right: 120px; /* Add space between buttons */
}
{% comment %} 
/* This will ensure text goes to the next line if too long */
.table td {
  max-width: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
} {% endcomment %}

/* This will apply a tooltip-like effect to show full name on hover */
.table td .full-name {
  display: block;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}



td a {
  margin: 10px;
  padding: 100px;
}
/* Responsive handling for smaller screens */
@media screen and (max-width: 600px) {
  .table td .full-name:hover {
    max-width: none;
  }
  .table td {
    white-space: normal;
  }
}

</style>
{% endblock extrastyle %}

{% block content %}
    <div class="grid grid-cols-2 gap-4 p-4">

    <div class="row">
    
      
        <!--[ Recent Users ] start-->
        <div class="col-xl-12 col-md-12">
          <div class="card Recent-Users">
    
            {% if data.team_data.items %}
    
              <div class="card-header">
                <h5>Dashboard
                  <a href="#" id="refreshLink" class="label theme-bg2 text-white f-12" ><i class="fa fa-refresh"></i>
                  </a>
                </h5>
                <div id="loadingMessage" style="display: none;">Please wait, the data is being updated...</div>

                <!-- Include jQuery library -->
                <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

                <script>
                  $(document).ready(function() {
                    $('#refreshLink').click(function(e) {
                      e.preventDefault(); // Prevent default link behavior (i.e., navigating to #)

                      // Show loading message while the update_repo process is running
                      $('#loadingMessage').show();

                      $.ajax({
                        url: 'update_repo/',
                        method: 'GET',
                        success: function(response) {
                          // Hide loading message after successful update_repo execution
                          $('#loadingMessage').hide();
                          // Reload the current page after successful update_repo execution
                          location.reload()
                        },
                        error: function(xhr, status, error) {
                          $('#loadingMessage').hide();
                          // Handle errors
                          console.error('Error:', error);
                        }
                      });
                    });
                  });
                </script>
              </div>

              <div class="card-block px-0 py-3">
                <div class="table-responsive">
                  <table class="table table-hover">

                    <thead>
                      <tr>
                        <th></th>
                        <th>Team Name</th>
                        <th>Number of branches</th>
                        <th>Branches behind main</th>
                        <th>Branches ahead main</th>
                        <th>Commit Quality</th>
                        <th>Moods</th>
                        <th>Time Stamp</th>
                      </tr>
                    </thead>
    
                    <tbody>
                        {% for team, data in data.team_data.items %}
    
                        <tr class="unread">
                          <td><img class="rounded-circle" style="width:40px;" src="{% static 'assets/images/user/avatar-1.jpg' %}"
                              alt="activity-user">
                          </td>
                         
                          <td>
                            <h6 class="mb-1">{{ team.teamName }}</h6>
                            {% comment %} <p class="m-0">{{ p.info }}</p> {% endcomment %}
                          </td>

                          <td>
                            <h6 class="text-muted">
                                <i>{{ data.repo.branchNumber }}</i>
                            </h6>
                          </td>

                          <td>
                            <h6 class="text-muted">
                                <i>{{ data.repo.branchBehindMax }}</i>
                            </h6>
                          </td>

                          <td>
                            <h6 class="text-muted">
                                <i>{{ data.repo.branchAheadMax }}</i>
                            </h6>
                          </td>

                          <td>
                            <h6 class="text-muted">
                                <i>{{ data.repo.commitQuality }}</i>
                            </h6>
                          </td>
                          
                          <td>
                            <h6 class="text-muted">
                              <i>{{ data.mood }}</i>
                            </h6>
                          </td>

                          <td>
                            <h6 class="text-muted">
                                <i>{{ data.repo.timeStamp }}</i>
                            </h6>
                          </td>

                          <td>
                            <a href="team_view/?teamName={{ team.teamName }}" class="label theme-bg2 text-white f-12">View</a>
                            <a href="suppressTeam/?teamName={{ team.teamName }}" class="label theme-bg text-white f-12"><i class="fa fa-trash"></i></a>
                          </td>
                        </tr>
    
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
                <div style="text-align: center;">
                  <a href="{% url 'dashboard:add_new_token' %}" style="display: inline-block; font-size: 32px;">
                      <i class="fa fa-plus-circle"></i>
                  </a>
              </div>
                            </div>
    
            {% else %}
            <div class="card-header">
              <h5>Dashboard
                <a href="#" id="refreshLink" class="label theme-bg2 text-white f-12" >Refresh
                </a>
              </h5>
              <div id="loadingMessage" style="display: none;">Please wait, the data is being updated...</div>

              <!-- Include jQuery library -->
              <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

              <script>
                $(document).ready(function() {
                  $('#refreshLink').click(function(e) {
                    e.preventDefault(); // Prevent default link behavior (i.e., navigating to #)

                    // Show loading message while the update_repo process is running
                    $('#loadingMessage').show();

                    $.ajax({
                      url: 'update_repo/',
                      method: 'GET',
                      success: function(response) {
                        // Hide loading message after successful update_repo execution
                        $('#loadingMessage').hide();
                        // Reload the current page after successful update_repo execution
                        location.reload()
                      },
                      error: function(xhr, status, error) {
                        $('#loadingMessage').hide();
                        // Handle errors
                        console.error('Error:', error);
                      }
                    });
                  });
                });
              </script>
            </div>

            <div class="card-block px-0 py-3">
              <div class="table-responsive">
                <table class="table table-hover">

                  <thead>
                    <tr>
                      <th></th>
                      <th>Team Name</th>
                      <th>Number of branches</th>
                      <th>Branches behind main</th>
                      <th>Branches ahead main</th>
                      <th>Commit Quality</th>
                      <th>Moods</th>
                      <th>Time Stamp</th>
                    </tr>
                  </thead>
  
                  <tbody>
                     
                  </tbody>
                </table>
              </div>
            </div>
              {% endif %}
{% endblock %}

webserver/templates/dashboard/select_repositories.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block extrastyle %}
<link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">
{% endblock extrastyle %}

{% block content %}
    <h2>Select Repositories</h2>

    <form method="post" action="{% url 'dashboard:add_new_token' %}">
        {% csrf_token %}
        
        <table>
          {{ form.as_table }}
        </table>
    
        <!-- Serialize the form data and include it as hidden fields -->
        {% for field in form %}
          {% if field.name != 'selected_repos' %} {# Exclude the selected_repos field #}
            <input type="hidden" name="{{ field.name }}" value="{{ field.value }}">
          {% endif %}
        {% endfor %}
        
        <label for="selected_repos">Select Repositories:</label>
        <select name="selected_repos" multiple>
          {% for repo in repos %}
            <option value="{{ repo }}">{{ repo }}</option>
          {% endfor %}
        </select>
        
        <button type="submit">Save Selected Repositories</button>
      </form>
    

{% endblock %}

webserver/templates/dashboard/token_form.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block extrastyle %}
<link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">
{% endblock extrastyle %}

{% block content %}
  <h2>Add teams</h2>
  <form method="post" action="{% url 'dashboard:add_new_token' %}">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Submit</button>
  </form>
{% endblock %}